import { setupWorker } from 'msw/browser'
import { handlers } from './handlers'

/**
 * Browser MSW worker for development and Storybook.
 * Intercepts network requests via Service Worker.
 *
 * Note: Requires public/mockServiceWorker.js to be present.
 * The service worker file should be generated by running:
 * `npx msw init public/ --save`
 */
export const worker = setupWorker(...handlers)
